---
title: "Helium Timeline 2011-2017"
---

```{r}
rm(list=ls())
graphics.off()
setpath <- "/MEGAsync/Work/HKU/CSRP"
setwd(sprintf("~%s", setpath))

setwd(sprintf("~%s/helium", setpath))
df <- readRDS("helium_cases_2011-17.rds")
```

```{r, fig.width = 16, fig.height = 10}
# plotting timeline (alternate method) ----
par(mar = rep(2, 4))
timelineS::timelineS(df[, c('info', 'date')], xlab = "2011", buffer.days = 14, scale = "year", scale.format = "%Y")
```

```{r, fig.width = 16, fig.height = 10}
# prepare for plotting timeline ----
library(ggplot2)
library(ggrepel) # geom_text_repel (replacing geom_text)
library(scales)
library(lubridate)
# http://benalexkeen.com/creating-a-timeline-graphic-using-r-and-ggplot2/

df$male <- as.factor(df$male)
directions <- c(1, -1) 

# positions <- c(0.5, -0.5, 1.0, -1.0, 1.5, -1.5)
# line_pos <- data.frame(
#   "date" = unique(df$date),
#   # "position"=rep(positions, length.out=length(unique(df$date))),
#   "position" = 0.05 + df$articles[-c(28)]/10,
#   "direction" = rep(directions, length.out=length(unique(df$date)))
# )
# df <- merge(x=df, y=line_pos, by="date", all = TRUE)

# df$direction <- rep(directions, length.out=length(df$date)) # alternating direction (up & down)
df$direction <- rep(1, length.out=length(df$date)) # only up direction

df$position <- (0 + df$articles/20)*df$direction # length of the vertical line (minimum value + number of articles scaled)

df <- df[with(df, order(date)), ]

text_offset <- 0.0
df$text_position <- (text_offset * df$direction) + df$position

month_buffer <- 0

month_date_range <- seq(min(df$date) - months(month_buffer), max(df$date) + months(month_buffer), by='month')
month_format <- format(month_date_range, '%b')
month_df <- data.frame(month_date_range, month_format)

year_date_range <- seq(min(df$date) - months(month_buffer), max(df$date) + months(month_buffer), by='year')
year_date_range <- as.Date(
  intersect(
    ceiling_date(year_date_range, unit="year"),
    floor_date(year_date_range, unit="year")
  ),  origin = "1970-01-01"
)
year_format <- format(year_date_range, '%Y')
year_df <- data.frame(year_date_range, year_format)

#### plotting timeline ####
timeline_plot<-ggplot(df,aes(x=date,y=0, col=male, label=male))
timeline_plot<-timeline_plot+labs(col="male")
timeline_plot<-timeline_plot # + scale_color_manual(values= c("#ae0000", "#005a9a"), drop = FALSE) # red for female, blue for male
timeline_plot<-timeline_plot+theme_classic()

# Plot horizontal black line for timeline
timeline_plot<-timeline_plot+geom_hline(yintercept=0, 
                                        color = "black", size=0.3)

# Plot vertical segment lines for milestones
timeline_plot<-timeline_plot+geom_segment(data=df, aes(y=position,yend=0,xend=date), size=0.3, linetype = 2) + scale_color_manual(values= c("#ae0000", "#005a9a"), drop = FALSE) # red for female, blue for male

# Plot scatter points at zero and date
timeline_plot<-timeline_plot+geom_point(aes(y=0), size=0)
timeline_plot<-timeline_plot+geom_point(aes(y=position), size=0) + scale_color_manual(values= c("#ae0000", "#005a9a"), drop = FALSE) # red for female, blue for male
# timeline_plot<-timeline_plot+geom_text(aes(y=0.03), size=3)

# Don't show axes, appropriately position legend
timeline_plot<-timeline_plot+theme(axis.line.y=element_blank(),
                                   axis.text.y=element_blank(),
                                   axis.title.x=element_blank(),
                                   axis.title.y=element_blank(),
                                   axis.ticks.y=element_blank(),
                                   axis.text.x =element_blank(),
                                   axis.ticks.x =element_blank(),
                                   axis.line.x =element_blank(),
                                   legend.position = "none"
)

# Show text for each month
timeline_plot<-timeline_plot+geom_text(data=month_df, aes(x=month_date_range,y = 0.027,label=month_format),size=2.5, vjust = 0.5, color='black', angle=45)
# Show year text
timeline_plot<-timeline_plot+geom_text(data=year_df, aes(x=year_date_range,y = -0.026,label=year_format, fontface="bold"),size=3, color='black')
# Show text for each milestone
timeline_plot<-timeline_plot+geom_label_repel(aes(y=position,label=info), size=2.7, force = 0.9, point.padding = NA)
print(timeline_plot)

```
